import express, { Router } from "express";
import { getSmartPhones } from "../controllers/inventoriesController";

const inventoryRoutes: Router = express.Router();

inventoryRoutes.get("/smartphones", getSmartPhones);

export default inventoryRoutes;

const smartphones = [
  {
    name: "Samsung Galaxy S20 Ultra",
    price: 999.99,
    quantity: 50,
    images: ["image1.jpg", "image2.jpg"],
    releasedDate: new Date("2022-01-01"),
    brand: "Samsung",
    model: "S20 Ultra",
    opSystem: "Android",
    storageCapacityGB: [128, 256],
    ram: [12, 16],
    processor:
      "Octa-core (1x3.3 GHz Cortex-X4 & 5x3.2 GHz Cortex-A720 & 2x2.3 GHz Cortex-A520)",
    screenSize: 6.78,
    color: "Mystic Black",
    cellularTechnology: "4G",
    battery: 5000,
    simCard: "Nano",
    camera: [50, 12],
    charger: 65,
    usbType: "USB Type-C",
    aboutThisPhone: "High-end smartphone with advanced camera features.",
    condition: "New",
    rating: 4.8,
    sells: 20,
    inStock: true,
  },
  {
    name: "Smartphone A",
    price: 699.99,
    quantity: 100,
    images: ["image1.jpg", "image2.jpg"],
    releasedDate: new Date("2022-01-15"),
    brand: "Samsung",
    model: "Galaxy S21",
    opSystem: "Android",
    storageCapacityGB: [128],
    ram: [8],
    processor: "Octa-core (2x2.8 GHz Cortex-A76 & 6x1.8 GHz Cortex-A55)",
    screenSize: 6.2,
    color: "Phantom Gray",
    cellularTechnology: "4G",
    battery: 4000,
    simCard: "Nano",
    camera: [12, 12],
    charger: 25,
    usbType: "USB Type-C",
    aboutThisPhone: "High-performance smartphone with a sleek design.",
    condition: "New",
    rating: 4.5,
    sells: 30,
    inStock: true,
  },
  {
    name: "Smartphone B",
    price: 899.99,
    quantity: 50,
    images: ["image3.jpg", "image4.jpg"],
    releasedDate: new Date("2022-02-10"),
    brand: "Apple",
    model: "iPhone 13 Pro",
    opSystem: "iOS",
    storageCapacityGB: [256],
    ram: [16],
    processor: "Hexa-core (2x3.23 GHz Monsoon & 4x1.59 GHz Mistral)",
    screenSize: 6.1,
    color: "Midnight Green",
    cellularTechnology: "5G",
    battery: 3095,
    simCard: "Nano",
    camera: [12, 12, 12],
    charger: 20,
    usbType: "Lightning",
    aboutThisPhone:
      "Latest iPhone with advanced features and stunning camera capabilities.",
    condition: "New",
    rating: 4.8,
    sells: 20,
    inStock: true,
  },
  {
    name: "Galaxy S20",
    price: 799.99,
    quantity: 50,
    images: ["image1.jpg", "image2.jpg"],
    releasedDate: new Date("2022-01-01"),
    brand: "Samsung",
    model: "S20",
    opSystem: "Android",
    storageCapacityGB: [128, 256],
    ram: [8, 12],
    processor:
      "Octa-core (2x2.73 GHz Mongoose M5 & 2x2.50 GHz Cortex-A76 & 4x2.0 GHz Cortex-A55)",
    screenSize: 6.2,
    color: "Blue",
    cellularTechnology: "4G",
    battery: 4000,
    simCard: "Nano",
    camera: [64, 12],
    charger: 25,
    usbType: "USB Type-C",
    aboutThisPhone: "Powerful flagship phone with a stunning display.",
    condition: "New",
    rating: 4.5,
    sells: 20,
    inStock: true,
  },
  {
    name: "iPhone 12",
    price: 899.99,
    quantity: 30,
    images: ["image3.jpg", "image4.jpg"],
    releasedDate: new Date("2022-02-15"),
    brand: "Apple",
    model: "12",
    opSystem: "iOS",
    storageCapacityGB: [64, 128, 256],
    ram: [4, 6],
    processor: "Hexa-core (2x3.1 GHz Firestorm & 4x1.8 GHz Icestorm)",
    screenSize: 6.1,
    color: "Silver",
    cellularTechnology: "5G",
    battery: 2815,
    simCard: "Nano",
    camera: [12, 12],
    charger: 20,
    usbType: "Lightning",
    aboutThisPhone: "Sleek and powerful iPhone with a superior camera system.",
    condition: "New",
    rating: 4.8,
    sells: 25,
    inStock: true,
  },
  {
    name: "OnePlus 9",
    price: 749.99,
    quantity: 40,
    images: ["image9.jpg", "image10.jpg"],
    releasedDate: new Date("2022-03-10"),
    brand: "OnePlus",
    model: "9",
    opSystem: "Android",
    storageCapacityGB: [128, 256],
    ram: [8, 12],
    processor:
      "Octa-core (1x3.2 GHz Kryo 585 & 3x2.42 GHz Kryo 585 & 4x1.8 GHz Kryo 585)",
    screenSize: 6.55,
    color: "Black",
    cellularTechnology: "5G",
    battery: 4500,
    simCard: "Nano",
    camera: [48, 50, 2],
    charger: 65,
    usbType: "USB Type-C",
    aboutThisPhone:
      "Flagship killer with top-notch performance and camera capabilities.",
    condition: "New",
    rating: 4.7,
    sells: 18,
    inStock: true,
  },
  {
    name: "Google Pixel 5",
    price: 699.99,
    quantity: 25,
    images: ["image11.jpg", "image12.jpg"],
    releasedDate: new Date("2022-04-05"),
    brand: "Google",
    model: "Pixel 5",
    opSystem: "Android",
    storageCapacityGB: [128],
    ram: [8],
    processor:
      "Octa-core (1x2.4 GHz Kryo 475 Prime & 1x2.2 GHz Kryo 475 Gold & 6x1.8 GHz Kryo 475 Silver)",
    screenSize: 6.0,
    color: "Sorta Sage",
    cellularTechnology: "5G",
    battery: 4080,
    simCard: "eSIM",
    camera: [12.2, 16],
    charger: 18,
    usbType: "USB Type-C",
    aboutThisPhone: "Pure Android experience with an impressive camera system.",
    condition: "New",
    rating: 4.6,
    sells: 15,
    inStock: true,
  },
];
